name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      USE_SSH: true
      GIT_USER: petyosi
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: | 
          pnpm install

      - name: run CI
        run: |
          pnpm ci
          pnpm run build

      - name: Release
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          pnpm run lerna:publish
